//fabric
export const FETCH_DATA = "FETCH_DATA";
export const FETCH_CREDITS = "FETCH_CREDITS";

//Bank
export const FETCH_BANK_DATA = "FETCH_BANK_DATA";
export const APPROVE_CREDIT_BY_BANK = "APPROVE_CREDIT_BY_BANK";
export const PAY_CREDIT_BY_BANK = "PAY_CREDIT_BY_BANK";
export const CLOSE_CREDIT_BY_BANK = "CLOSE_CREDIT_BY_BANK";

//Credit
export const FETCH_CREDIT_DATA = "FETCH_CREDIT_DATA";

